config/routes.rb
Pinteresting::Application.routes.draw do
  get 'homes/show'

  resources :pins
  
  devise_for :users
  root "pins#index"
  get "about" => "pages#about" # creates about_path

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	validates :description, presence: true
	# validates :image, presence: true
	validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :pins  

   validates :name, presence: true    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 16)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end
  
  def edit
  end
 
  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end
 
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    @pin.destroy
    redirect_to pins_url, notice: 'Pin was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by(id: params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            <li>
              <button type="button" class="btn btn-default navbar-btn btn-sm">
                <%= link_to new_pin_path do %>
                  <span class="glyphicon glyphicon-pushpin"></span> 
                    New Pin
                <% end %>
              </button>
            </li>
            <li>
              <button type="button" class="btn btn-danger navbar-btn btn-sm">
              <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
              </button>
            </li>
              <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container body">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info alert-dismissable") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Welcome to Pinteresting</h1>
		<p>You can pin all kinds of stuff here. From pictures of cats, to Jimmy Fallons broken fingers.</p>
		<p>
			<%= link_to "Login", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>	
		</p>
</div>

app/views/pages/about.html.erb
<div class="about-sections odd center">
  	<h1>About Me</h1>
	<p>This is the Pinteresting app that I created as part of the one month rails training class. </p>
</div>

<div class="about-sections even">
	<div class="row">
	  	<div class="col-md-6">
	  		<%= image_tag("1449200612_laptop.png", :alt => "Laptop", :width => "250px") %>
	  	</div>
  		<div class="col-md-6">
  			<h2>Pin Whatever You Want!</h2>
  			<ul class="list-styled">
  				<li>Cars</li>
  				<li>People</li>
  				<li>Skateboards</li>
  				<li>Sunsets</li>
  				<li>Kittens</li>
  				<li>Puppies</li>
  				<li>Hockey Players</li>
  			</ul>
  		</div>
	</div>	
</div>
<div class="jumbotron odd center">
	<h2>Lets Start Pinning</h2>
	<p>Click the button below to start pinning all the magical things!</p>
	<button type="button" class="btn btn-default btn-lg">
    <%= link_to new_pin_path do %>
      <span class="glyphicon glyphicon-pushpin"></span> 
        New Pin
    <% end %>
  </button>

</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id ="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <%= link_to pin do %>
        <span class="panel-body show-description">
          <p class="pin-title"><%= pin.title %></p>
          <p class="pin-description"><%= pin.description %></p>
          <span class="user-email"><%= pin.user.name if pin.user %></span>
        </span>
        <% end %>
        <% if pin.user == current_user %>
          <div class="panel-footer actions center">
            <button type="button" class="btn btn-default btn-sm">
              <%= link_to edit_pin_path(pin) do %>
                <span class="glyphicon glyphicon-edit"></span>
                Edit
              <% end %>
            </button>
            <button type="button" class="btn btn-danger btn-sm delete">
              <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <span class="glyphicon glyphicon-trash"></span>
                Delete
              <% end %>
            </button>

          </div>
        <% end %>
    </div>
  <% end %>
</div>

<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class="row">
    <div class="col-md-offset-3 col-md-6">
		<div class="panel panel-default">
		  <div class="panel-heading">
		    <div class="panel-title">
		    	<h1>New Pin</h1>
		    </div>
			  </div>
			  <div class="panel-body">
			    <%= render 'form' %>
			  </div>
		</div>
	</div>
</div>

app/views/pins/show.html.erb
<div class="container">
  <%= link_to 'Back', pins_path %>

  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading center">
          <%= image_tag @pin.image.url(:medium) %>
        </div>
        <div class="panel-body">
          <p class="pin-title"><%= @pin.title %></p>
          <p class="pin-description"><%= @pin.description %></p>
          <span class="user-email"><%= @pin.user.name if @pin.user %></span>
          <div class="social-sharing" style="padding-top:8px;">
            <span class="user-email">Share this pin:</span>
            <%= social_share_button_tag(@pin.title, :popup => "true") %>
        </div>
      </div>
          <% if @pin.user == current_user %>
            <div class="panel-footer actions center">
              <button type="button" class="btn btn-default btn-sm">
                <%= link_to edit_pin_path(@pin) do %>
                  <span class="glyphicon glyphicon-edit"></span>
                  Edit
                <% end %>
              </button>
              <button type="button" class="btn btn-danger btn-sm delete">
                <%= link_to @pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <span class="glyphicon glyphicon-trash"></span>
                  Delete
                <% end %>
              </button>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>